export type WsMessageType =
  | "hello" | "hello_ack"
  | "send" | "ack" | "push"
  | "list_peers" | "peers_list"
  | "set_status" | "set_summary" | "set_visible" | "set_profile" | "set_stats"
  | "join_group" | "leave_group"
  | "set_state" | "get_state" | "list_state" | "state_result" | "state_list_result" | "state_changed"
  | "remember" | "memory_stored" | "recall" | "recall_result" | "forget"
  | "schedule" | "schedule_ack" | "list_scheduled" | "scheduled_list" | "cancel_scheduled" | "cancel_scheduled_ack"
  | "message_status" | "message_status_result"
  | "upload_file" | "file_url" | "list_files" | "files_list" | "file_status" | "file_status_result" | "delete_file" | "grant_file_access"
  | "vector_store" | "vector_stored" | "vector_search" | "vector_results" | "vector_delete" | "list_collections" | "collections_list"
  | "graph_query" | "graph_result" | "graph_execute"
  | "share_context" | "list_contexts" | "contexts_list" | "get_context" | "context_results"
  | "create_task" | "task_created" | "list_tasks" | "tasks_list" | "claim_task" | "complete_task"
  | "mesh_query" | "mesh_query_result" | "mesh_execute" | "mesh_schema" | "mesh_schema_result"
  | "create_stream" | "stream_created" | "publish" | "subscribe" | "stream_data" | "list_streams" | "streams_list"
  | "mcp_register" | "mcp_registered" | "mcp_list" | "mcp_list_result" | "mcp_call" | "mcp_call_result" | "mcp_call_forward" | "mcp_call_response" | "mcp_remove"
  | "mcp_deploy" | "mcp_deploy_result" | "mcp_undeploy" | "mcp_update" | "mcp_logs" | "mcp_logs_result" | "mcp_schema" | "mcp_schema_result" | "mcp_catalog" | "mcp_catalog_result" | "mcp_scope" | "mcp_scope_result"
  | "vault_set" | "vault_ack" | "vault_list" | "vault_list_result" | "vault_delete"
  | "mesh_watch" | "watch_ack" | "mesh_unwatch" | "mesh_watches" | "watches_list" | "watch_triggered"
  | "create_webhook" | "webhook_created" | "list_webhooks" | "webhooks_list" | "delete_webhook"
  | "share_skill" | "skill_shared" | "get_skill" | "skill_result" | "list_skills" | "skills_list" | "remove_skill" | "skill_deploy" | "skill_deploy_result"
  | "mesh_info" | "mesh_info_result" | "mesh_stats" | "mesh_stats_result" | "mesh_clock" | "mesh_clock_result"
  | "mesh_set_clock" | "mesh_pause_clock" | "mesh_resume_clock"
  | "ping" | "pong"
  | "peer_file_request" | "peer_file_response" | "peer_dir_request" | "peer_dir_response"
  | "error";
